volumes:
  postgres_storage:
  qdrant_storage:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_SECURE_COOKIE=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
  env_file:
    - path: .env
      required: true

services:

  napkin-exchange-proxy:

    container_name: napkin-exchange-proxy

    image: nginxproxy/nginx-proxy

    restart: unless-stopped

    ports:

      - 80:80

      - 443:443

    volumes:

      - /var/run/docker.sock:/tmp/docker.sock:ro

      - /var/docker/nginx/html:/usr/share/nginx/html

      - /var/docker/nginx/certs:/etc/nginx/certs

      - /var/docker/nginx/vhost:/etc/nginx/vhost.d

    logging:

      options:

        max-size: "10m"

        max-file: "3"

  napkin-exchange-letsencrypt:

    container_name: napkin-exchange-letsencrypt

    image: jrcs/letsencrypt-nginx-proxy-companion

    restart: unless-stopped

    volumes_from:

      - napkin-exchange-proxy

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock

      - /var/docker/nginx/acme:/etc/acme.sh

    environment:

      DEFAULT_EMAIL: troy@callistosystems.online
   
   ####################################
   ###
   ###
   ####################################
   
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    user: "1000:1000"  # <--- Runs container process as root
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - ./data/node:/home/node/.n8n
      - ./data/demo:/demo-data
      - ./data/shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
     
    expose:
    
      - 5678
      
    environment:
      
      WEBHOOK_URL: https://automation.valorantdigital.online/
      
      VIRTUAL_PORT: 5678
      
      VIRTUAL_HOST: automation.valorantdigital.online
      
      LETSENCRYPT_HOST: automation.valorantdigital.online        
      
      N8N_DIAGNOSTICS_ENABLED: false
      
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
